### ISSUE TITLE
Libs published only for Scala 3 are not found

### ISSUE THREAD

**Issue by carlosedp** [Baccata/vscode-scaladex-search#11]
Due to the filtering [here](https://github.com/Baccata/vscode-scaladex-search/blob/27e540aec944de3565a501ccef54392dc717d529/src/main/scala/scaladex.scala#L9), Scala libs published only for Scala 3 like one [I publish](https://index.scala-lang.org/carlosedp/zio-channel) are not found.

**Comment by Baccata** [comment]
What would be your preferred solution ? 

We could have a vscode setting for preferred Scala version. I'm not sure I want to add another prompt for the version ...

**Comment by carlosedp** [comment]
I thought maybe querying scaladex twice, one for 2.13 and another for 3... then merging and deduping the json results.

This way it would avoid the user from defining parameters. Since choosing the lib via the extension already doesn't guarantees that the lib and version selected is compatible with the current project, this wouldn't make too much of a difference.

What do you think?

**Comment by carlosedp** [comment]
I've pushed #12 but be welcome to change it if desired :)

**Comment by carlosedp** [comment]
Weird... in the dev version it finds my scala 3 only lib... but in the latest 0.3.4 that is published, it doesn't:

![image](https://github.com/Baccata/vscode-scaladex-search/assets/20382/0b0b7dad-a618-4933-a6d3-08c07d1a0e52)


![image](https://github.com/Baccata/vscode-scaladex-search/assets/20382/b0550595-d4f2-4bde-9777-ae2965026d34)

In the dev version locally (from main branch):

![image](https://github.com/Baccata/vscode-scaladex-search/assets/20382/31630b08-3dd3-42e8-8876-44b41ee95eb3)

**Comment by Baccata** [comment]
I'll give it a look

**Comment by Baccata** [comment]
So, interestingly I had the same behaviour as you've experienced. I went to the extension window in vscode, and there was a "reload required" button appearing next to the scaladex search extension. I clicked, it restared the editor, and I'm now seeing your library.

**Comment by carlosedp** [comment]
Weird... I closed all vscode windows, reopened and had the same result.

I'm currently traveling on vacations so can't test it but will report in some days :)

**Comment by carlosedp** [comment]
Hey, back...

I tried again... tried removing the extension and re-adding but it still doesn't find the lib.

Even tried creating a new profile with only the scaladex and metals extensions but same results... no lib show.

**Comment by Baccata** [comment]
not sure what to tell you, except that it works on my machine 😞. I've uninstalled the extension, reloaded my editor, and re-installed it and it works :/ 

<img width="1658" alt="Screenshot 2023-09-14 at 11 56 26" src="https://github.com/Baccata/vscode-scaladex-search/assets/4439335/533af7ec-9b44-46cd-a855-9c4e774ecea5">


<img width="1663" alt="Screenshot 2023-09-14 at 11 56 37" src="https://github.com/Baccata/vscode-scaladex-search/assets/4439335/611371ff-bde0-4a53-b71d-55f8a3b5ad71">

**Comment by Baccata** [comment]
@carlosedp, no luck ?

**Comment by carlosedp** [comment]
Weirdly enough... on my daily VSCode (Mac), doesn't work. I've installed the VSCode Insiders, synched to my account to get the extensions and it worked fine... also in my other computer, a Windows 11 PC with all extensions it worked as well... 

Who knows! I think i'll close this since it's not the extension but my system.
Thanks!

**Comment by carlosedp** [comment]
BTW, I just tried removing everything and reinstalling VSCode (I forgot a temp dir when I tried a while back) and it worked...

Thanks and sorry about the noise :)

**Comment by Baccata** [comment]
Np, glad it got sorted 👍
