### ISSUE TITLE
Listing modules of library brings up a bizarre number of them

### ISSUE THREAD

**Issue by kubukoz** [Baccata/vscode-scaladex-search#3]
1. Search for library

<img width="919" alt="image" src="https://user-images.githubusercontent.com/894884/147427430-a02eef6a-fef2-4f1e-b920-b8a05f61567e.png">

2. Press enter, wait

3. No profit:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/894884/147427447-9bb32a46-b6ed-4474-bf47-fd178ed536f3.png">

This must've happened within the last 1-2 weeks, potentially because of a change in Scaladex.

**Comment by Baccata** [comment]
Bug raised upstream : https://github.com/scalacenter/scaladex/issues/788

In the meantime could add a call to `.distinct ` here : https://github.com/Baccata/vscode-scaladex-search/blob/master/src/main/scala/extension.scala#L71

**Comment by Baccata** [comment]
This was fixed upstream
