### ISSUE TITLE
Wrong artifact organization

### ISSUE THREAD

**Issue by kubukoz** [Baccata/vscode-scaladex-search#5]
For example, when you search for log4cats and want to use the `typelevel` version, you will still end up using `io.chrisdavenport` as the org name. For example, for log4cats-noop 2.5.0 in a scala-cli script:

`//> using lib "io.chrisdavenport::log4cats-noop:2.5.0"`

**Comment by Baccata** [comment]
This is not a bug in this extension. It's a bug in Scaladex : 

https://index.scala-lang.org/api/project?organization=typelevel&repository=log4cats
